---
title: "coronavirus"
author: "Benjamin Villa"
date: "3/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(ggplot2)
library(infer)
library(dplyr)
library(gt)
library(tidyr)
library(readr)
library(purrr)
library(tibble)
library(stringr)
library(forcats)
library(janitor)
library(tidyselect)
library(DataExplorer)
library('remotes')
library('nCov2019')
options(scipen = 999)


```

```{r}
remotes::install_github("GuangchuangYu/nCov2019", dependencies = TRUE, forece = TRUE)

library(ggplot2)
y <- load_nCov2019(lang = 'en')
d <- y['global']
max_time <- max(d$time)
min_time <- max_time - 7
d <- na.omit(d[d$time >= min_time & d$time <= max_time,])
dd <- d[d$time == max(d$time, na.rm = TRUE),]
d$country <- factor(d$country, 
  levels=unique(dd$country[order(dd$cum_confirm)]))
breaks = c(10, 100, 1000, 10000)
ggplot(d, aes(time, country)) + 
  geom_tile(aes(fill = cum_confirm), color = 'black') + 
  scale_fill_viridis_c(trans = 'log', breaks = breaks, 
  labels = breaks) + 
  xlab(NULL) + ylab(NULL) +
  scale_x_date(date_labels = "%Y-%m-%d") + theme_minimal()
```

```{r}

```




```{r}

require(dplyr)
require(ggplot2)
require(shadowtext)
require(nCov2019)

d <- load_nCov2019()
dd <- d['global'] %>% 
  as_tibble %>%
  rename(confirm=cum_confirm) %>%
  filter(confirm > 100) %>%
  group_by(country) %>%
  mutate(days_since_100 = as.numeric(time - min(time))) %>%
  ungroup 
  

  

#breaks=c(100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000)


p <- ggplot(dd, aes(days_since_100, confirm, color = country)) +
  geom_line(size = 0.8) +
  geom_point(pch = 21, size = 1) +
  scale_y_log10(expand = expansion(add = c(0,0.1)), 
                breaks = breaks, labels = breaks) +
  scale_x_continuous(expand = expansion(add = c(0,1))) +
  theme_minimal(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    legend.position = "none",
    plot.margin = margin(3,15,3,3,"mm")
  ) +
  coord_cartesian(clip = "off") +
  geom_shadowtext(aes(label = paste0(" ",country)), hjust=0, vjust = 0, 
                  data = . %>% group_by(country) %>% top_n(1, days_since_100), 
                  bg.color = "white") +
  labs(x = "Number of days since 100th case", y = "", 
       subtitle = "Total number of cases")
print(p)



```

```{r}

require(dplyr)
require(ggplot2)
require(shadowtext)
require(nCov2019)

d <- load_nCov2019()
dd <- d['global'] %>% 
  as_tibble %>%
  rename(confirm=cum_confirm) %>%
  filter(confirm > 100) %>%
  group_by(country) %>%
  mutate(days_since_100 = as.numeric(time - min(time))) %>%
  ungroup 


p <- ggplot(dd, aes(days_since_100, confirm, color = country)) +
  geom_line(size = 0.2) +
  scale_y_log10(expand = expansion(add = c(0,0.1)), 
                breaks = breaks, labels = breaks) +
  scale_x_continuous(expand = expansion(add = c(0,1))) +
  theme_minimal(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    legend.position = "none",
    plot.margin = margin(3,15,3,3,"mm")
  ) +
  coord_cartesian(clip = "off") +
  labs(x = "Number of days since 100th case", y = "", 
       subtitle = "Total number of cases") + 
  geom_text(aes(label = country, size= max(confirm)),
            #check_overlap = TRUE,
            size = 1
            ) +
 theme(
  panel.background = element_rect(fill = "black",
                                colour = "black"),
  panel.grid.major = element_line(size = 0, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0, linetype = 'solid',
                                colour = "white"),
  plot.background = element_rect(fill = "black"))

print(p)



```


